import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { getCartCount } from "@/data/shop/getCartCount";
import { getUnreadMsgs } from "@/data/account/notifications/actions";
import { CartInitializer } from "@/components/navigation/CartInitializer";
import { MessagesInitializer } from "@/components/navigation/MessagesInitializer";

import { SessionProvider } from "next-auth/react";
const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space-grotesk",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cartCount = await getCartCount();
  const messagesCount = await getUnreadMsgs();
  return (
    <html lang="en" className={`${spaceGrotesk.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col font-sans">
        <SessionProvider>
          <CartInitializer count={cartCount} />
          <MessagesInitializer count={messagesCount} />
          <Toaster position="top-center" />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
